# S1 — NumPy 與向量化思維

> **時間**：2 小時（講授 70min + 課堂練習 40min + QA 10min）  
> **資料**：`datasets/ecommerce/products.csv`  
> **學完能幹嘛**：用「一行程式」取代 for-loop，處理上百萬筆數字比 Excel 快 100 倍

---

## 為什麼資料人一定要會 NumPy？

做資料分析時，你會遇到的場景：

- 要把 **10 萬筆訂單金額**同時打 9 折 → 用 for-loop 要寫 5 行、跑 3 秒；用 NumPy **1 行、0.01 秒**
- 要算**每個商品的庫存總值**（價格 × 庫存）→ NumPy 一個乘號就搞定
- Pandas、scikit-learn、TensorFlow 底層**全部**都是 NumPy

**一句話口訣：寫 for-loop 處理數字的那一刻，你就輸了。**


---
## 核心觀念 1／3 — ndarray：N 維陣列

**定義**：ndarray 是一個「同型別、固定大小」的多維陣列。跟 Python list 的差別：

| 比較項 | Python list | NumPy ndarray |
|---|---|---|
| 元素型別 | 可混合 | 必須同型別 |
| 速度 | 慢 | 快 10~100 倍 |
| 記憶體 | 耗 | 省 |
| 向量化運算 | ❌ 要 for-loop | ✅ 直接運算 |


In [2]:
import numpy as np

In [ ]:
import numpy as np

# 從 list 建立
arr = np.array([1, 2, 3, 4, 5])
print('arr       =', arr)
print('shape     =', arr.shape)    # (5,)  → 一維，5 個元素
print('dtype     =', arr.dtype)    # int64
print('ndim      =', arr.ndim)     # 1

# 二維陣列（矩陣）
mat = np.array([[1, 2, 3], [4, 5, 6]])
print('\nmat       =\n', mat)
print('mat.shape =', mat.shape)    # (2, 3)

# 常用快速建立
print('\nzeros:', np.zeros(5))
print('\nzeros:', np.zeros([5,5])) # 補充
print('ones :', np.ones(3))
print('range:', np.arange(0, 10, 2))  # 0~10 每隔 2
print('linsp:', np.linspace(0, 1, 5)) # 0~1 均分 5 個

arr       = [1 2 3 4 5]
shape     = (5,)
dtype     = int64
ndim      = 1

mat       =
 [[1 2 3]
 [4 5 6]]
mat.shape = (2, 3)

zeros: [0. 0. 0. 0. 0.]

zeros: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
ones : [1. 1. 1.]
range: [0 2 4 6 8]
linsp: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
import sys, os  # 跟系統有關德
sys.path.insert(0, os.path.abspath('..')) #寫道系統環境變數
# abspath('..') 絕對路徑
from common.checker import check

In [6]:
os.path.abspath('..')

'c:\\Users\\student\\AIPE_class\\python_DB\\Sunny\\iSpan_python-DA-cookbooks\\Special-Edition_python_DA\\Python_DA_Course'

**口訣**：`np.array()` 把 list 變陣列，`.shape` 看形狀，`.dtype` 看型別。


> ### 💡 知識補給站 — Why ndarray is 100x Faster than list
> 
> Python list 是一個「**指標陣列**」— 每個元素可能散落在記憶體的不同位置，CPU 每次都要跳到新地址去找資料。
> 
> ndarray 是一塊「**連續記憶體 (contiguous C-array)**」— 所有元素緊密排列在一起，CPU 可以像翻書一樣從頭讀到尾，配合 **CPU cache** 極度高效。
> 
> 類比：list 像把 100 張發票塞在不同抽屜，每張都要開抽屜找；ndarray 像把 100 張發票排在同一本資料夾裡，翻頁就好。
> 
> 這也是為什麼 ndarray 要求「**同型別 (homogeneous dtype)**」— 每格大小一致才能連續排列，這是速度的代價。
> 
> *延伸關鍵字：memory layout, CPU cache locality, contiguous array, homogeneous dtype*

---
## 核心觀念 2／3 — 索引、切片、布林遮罩

三種取值方法，**布林遮罩**是資料分析最常用的。


In [5]:
a = np.array([10, 20, 30, 40, 50, 60])

# 1) 單點索引（和 list 一樣）
print('a[0]   =', a[0])    # 10
print('a[-1]  =', a[-1])   # 60（倒數第一個）

# 2) 切片 [start:stop:step]
print('a[1:4] =', a[1:4])  # [20 30 40]
print('a[::2] =', a[::2])  # [10 30 50]（每隔一個）

# 3) 布林遮罩（最重要！）
mask = a > 30
print('\nmask       =', mask)   # [F F F T T T]
print('a[mask]    =', a[mask])  # [40 50 60], 把 mask 當作條件直接取T的值
print('a[a > 30]  =', a[a > 30])  # 一步到位

# 多條件：用 & (and), | (or)，記得加括號！
print('a[(a > 20) & (a < 60)] =', a[(a > 20) & (a < 60)])

a[0]   = 10
a[-1]  = 60
a[1:4] = [20 30 40]
a[::2] = [10 30 50]

mask       = [False False False  True  True  True]
a[mask]    = [40 50 60]
a[a > 30]  = [40 50 60]
a[(a > 20) & (a < 60)] = [30 40 50]


In [8]:
a = np.array([1, 2, 3, 4, 5, 6])
a[ a%2 == a]

array([1])

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
a[ a%2 == 1]

array([1, 3, 5])

**口訣**：`a[條件]` 直接篩，多條件要加**括號**、用 `&` `|`（不是 `and` `or`）。


---
## 核心觀念 3／3 — 向量化運算與廣播

**向量化 (vectorization)**：陣列之間直接做數學運算，**不用 for-loop**。  
**廣播 (broadcasting)**：形狀不同的陣列也能運算，NumPy 會自動補齊。


In [10]:
# 向量化：兩個陣列逐元素相加 / 相乘
prices = np.array([100, 200, 300, 400]) 
# 在數學上是直的
qty    = np.array([  2,   1,   3,   5])
# 這也是直的

total = prices * qty        # → [200, 200, 900, 2000] , 就是向量化
# 不是內積
# 內積有另一個寫法
# 這是 底層C 的寫法
print('total =', total)
print('合計  =', total.sum())

# 廣播：陣列 × 單一數字
discounted = prices * 0.9   # 全部打 9 折
print('\n打折後 =', discounted)

total = [ 200  200  900 2000]
合計  = 3300

打折後 = [ 90. 180. 270. 360.]


In [ ]:
# 🔥 效能比較：for-loop vs 向量化
import time

big = np.random.rand(1_000_000)

# 方法 1：for-loop（慢）
t0 = time.time()
result1 = [x * 2 + 1 for x in big] 
#　8 和 15 行是重點
t1 = time.time()
print(f'for-loop   耗時: {(t1-t0)*1000:.1f} ms')

# 方法 2：向量化（快）
t0 = time.time()
result2 = big * 2 + 1
t1 = time.time()
print(f'向量化     耗時: {(t1-t0)*1000:.1f} ms')

print('\n兩者結果相同嗎？', np.allclose(result1, result2))

for-loop   耗時: 126.7 ms
向量化     耗時: 7.7 ms

兩者結果相同嗎？ True


**口訣**：看到 for-loop 在跑數字運算，99% 可以改成向量化。


In [8]:
# 💡 知識補給站 demo — Broadcasting 視覺化
a = np.arange(3).reshape(3, 1)   # shape (3,1)
b = np.arange(4).reshape(1, 4)   # shape (1,4)

print(a)
print(b)

[[0]
 [1]
 [2]]
[[0 1 2 3]]


In [13]:
print(f'a shape: {a.shape}, b shape: {b.shape}')


a shape: (3, 1), b shape: (1, 4)


In [9]:
print(a * b) # 元素相乘
# 但 a 是 3X1, b 是 1X4, 所以要擴展
# a 變成 3X3 ,b 變 3X4

[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]]


In [10]:
# 💡 知識補給站 demo — Broadcasting 視覺化
a = np.arange(3).reshape(3, 1)   # shape (3,1)
b = np.arange(4).reshape(1, 4)   # shape (1,4)
print(f'a shape: {a.shape}, b shape: {b.shape}')
print(f'a * b shape: {(a * b).shape}')   # → (3, 4)
print(a * b)

a shape: (3, 1), b shape: (1, 4)
a * b shape: (3, 4)
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]]


In [11]:
# 1. 如果兩個陣列的維度數不同，較少維度的那個在**前面補 1**
# 2. 兩個維度的 size 必須**相同**，或其中一個是 **1**
# 3. Size 為 1 的那個維度會被「拉長」到對方的 size

import numpy as np

a = np.arange(3).reshape(3, 1)
b = np.arange(4)   # 升維 (1, 4)
print("a.shape =", a.shape)
print("b.shape =", b.shape)
# 
c = a*b
print("c.shape =", c.shape)



a.shape = (3, 1)
b.shape = (4,)
c.shape = (3, 4)


In [12]:
import numpy as np

a = np.arange(3).reshape(3, 1)
b = np.arange(4)   # 升維 (1, 4)
print(b)

[0 1 2 3]


In [18]:
x = np.arange(6).reshape(2, 3)
y = np.array([[10], [20]])

print(x)
print(y)
print(y.shape)
print(x.shape)
print(x*y)

[[0 1 2]
 [3 4 5]]
[[10]
 [20]]
(2, 1)
(2, 3)
[[  0  10  20]
 [ 60  80 100]]


In [14]:
# y 的第二個維度是1 , 會被拉長成 3
print("y expaned to match x :")
print(np) # y 擴展到 x

y expaned to match x :
<module 'numpy' from 'c:\\Users\\jolin\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\numpy\\__init__.py'>


> ### 💡 知識補給站 — Broadcasting 三條規則
> 
> 廣播不是魔法，NumPy 遵守三條嚴格規則（從**最後一個維度**開始比對）：
> 
> 1. 如果兩個陣列的維度數不同，較少維度的那個在**前面補 1**
> 2. 兩個維度的 size 必須**相同**，或其中一個是 **1**
> 3. Size 為 1 的那個維度會被「拉長」到對方的 size
> 
> 類比：Excel 公式 `=A1:A100 * B1` → B1 就是被「廣播」到 100 列。如果規則不符合，NumPy 會報 `ValueError: operands could not be broadcast together`。
> 
> *延伸關鍵字：broadcasting rules, shape compatibility, dimension alignment*

---
## 實務 Case — 電商商品庫存分析

**情境**：行銷部要你快速回答三個問題：
1. 全站總庫存價值（unit_price × stock_qty 加總）是多少？
2. 有幾個商品庫存 < 20（快要缺貨）？
3. 如果所有商品都打 8 折，每件商品的新價格是多少？

我們只用 **NumPy**（Pandas 下節再學）。


In [20]:
import numpy as np

# 直接用 np.genfromtxt 讀 CSV（跳過標題列）
DATA = '../datasets/ecommerce/products.csv'
# gen from txt
prices = np.genfromtxt(DATA, delimiter=',', skip_header=1, usecols=3)  # unit_price
# delimiter, 去找電腦圖形介面的檔案, 用 Notepad ++ 開啟, 就是裡面的逗號(,)
stocks = np.genfromtxt(DATA, delimiter=',', skip_header=1, usecols=4)  # stock_qty

#print(prices)
print('商品數 =', len(prices))
print('前 5 筆價格:', prices[:5])
print('前 5 筆庫存:', stocks[:5])

商品數 = 30
前 5 筆價格: [1627. 1875.  620. 1718.  290.]
前 5 筆庫存: [ 12. 125.  52. 279. 216.]


In [ ]:
# Q1: 全站總庫存價值
inventory_value = prices * stocks          # 向量化：每個商品的庫存值
total_value = inventory_value.sum()
print(f'Q1 ▸ 全站庫存總值 = NT$ {total_value:,.0f}')
# :,.0f , 冒號: 宣告, 逗號, 千分位分隔符, 點 處理小數點後的位數, 數字(0) 代表精確度, f 控制小數點


# Q2: 庫存 < 20 的商品數（布林遮罩）
low_stock = stocks < 20 #　stocks < 20　, mask 用法
print(f'Q2 ▸ 快缺貨商品數 = {low_stock.sum()} 件')
print(f'     對應價格範圍: {prices[low_stock].min():.0f} ~ {prices[low_stock].max():.0f}')

# Q3: 全部打 8 折（廣播）
discounted = prices * 0.8
print(f'\nQ3 ▸ 前 5 個打折後價格: {discounted[:5]}')

Q1 ▸ 全站庫存總值 = NT$ 4,922,341
Q2 ▸ 快缺貨商品數 = 2 件
     對應價格範圍: 1506 ~ 1627

Q3 ▸ 前 5 個打折後價格: [1301.6 1500.   496.  1374.4  232. ]


**回顧**：三個商業問題，各用 **1 行 NumPy** 解決。如果換成 for-loop 至少要寫 15 行以上。


> ### 💡 知識補給站 — When Data Doesn't Fit in Memory
> 
> 本課的 `products.csv` 只有幾十 KB，但真實工作中的 log 檔、交易紀錄可能幾十 GB，遠超電腦記憶體。
> 
> **三個層級的處理策略**：
> - **小資料（< 1 GB）**：直接用 Pandas 讀進來，今天的做法就夠了
> - **中資料（1~10 GB）**：用 `pd.read_csv(path, chunksize=10000)` 分批讀取、逐批累加（S2 會教）
> - **大資料（> 10 GB）**：換引擎 — **Dask** 或 **Polars** 的語法幾乎和 Pandas 一樣，但能處理超過 RAM 的資料
> 
> 類比：你不會把整座圖書館搬回家才開始查資料，你會**一次借幾本** → 這就是 chunked processing 的概念。
> 
> *延伸關鍵字：chunked processing, Dask, Polars, out-of-core computing*

---
## 課堂練習（40 min）

以下三題難度遞增，不會就看回上面的範例。

### 🟢 送分題
建立一個 `np.array`，內容是 `[10, 20, 30, 40, 50]`，計算：
1. 所有元素的平均
2. 所有元素乘以 2 之後的結果
3. 篩出大於 25 的元素


In [22]:
# TODO: 你的程式碼
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
a_sum = arr.sum()/len(arr)
print(np.mean(arr))
 
print(a_sum)
b = [2]
print(arr * b)


mask = arr > 25
print('a[a > 30]  =', arr[arr > 25])  # 一步到位





30.0
30.0
[ 20  40  60  80 100]
a[a > 30]  = [30 40 50]


### 🟡 核心題
使用 `products.csv`，算出：
1. 單價 > 1000 的商品總共有幾個？
2. 庫存最多的前 3 個商品的**索引位置**（提示：`np.argsort`）
3. 假設「單價 < 500 的商品」全部進貨 50 個，這些商品總共要花多少錢？


In [25]:
import numpy as np

# 直接用 np.genfromtxt 讀 CSV（跳過標題列）
DATA = '../datasets/ecommerce/products.csv'
# gen from txt
prices = np.genfromtxt(DATA, delimiter=',', skip_header=1, usecols=3)  # unit_price
# delimiter, 去找電腦圖形介面的檔案, 用 Notepad ++ 開啟, 就是裡面的逗號(,)
stocks = np.genfromtxt(DATA, delimiter=',', skip_header=1, usecols=4)  # stock_qty

print(len(stocks[prices > 1000]))

np.argsort(stocks)
#　用stocks 的索引值作排列
print(np.argsort(stocks))
# 所以 這邊 print 出來後是從小排到大
a = np.argsort(stocks*(-1))
# 給一個 -1 讓他變成從大排到小
print(a)
sorted = (a[:3])
# 找 a 的前3筆
print(sorted)

# mask2 = prices < 500
total_p = prices[prices < 500]*50
print(total_p.sum())






16
[10  0 17 22 24  5 25  2 11 13 23  1 29 20 14 12 16 28 21 27 19 15  4  9
 26  6 18  3  8  7]
[ 7  3  8 18  6 26  9  4 15 19 27 21 28 16 12 14 20 29  1 23 13 11  2 25
  5 24 22 17  0 10]
[7 3 8]
120300.0


### 🔴 挑戰題
為了備戰雙 11，公司規則：
- 庫存 ≥ 100：打 7 折
- 庫存 20~99：打 9 折
- 庫存 < 20：原價（快缺貨不能再便宜）

請用**向量化**（不要 for-loop）算出每個商品的雙 11 售價。  
提示：`np.where(條件, 值A, 值B)` 可以**巢狀**使用。


In [ ]:
# TODO: 你的程式碼
import numpy as np
DATA = '../datasets/ecommerce/products.csv'
# gen from txt
prices = np.genfromtxt(DATA, delimiter=',', skip_header=1, usecols=3)
stocks = np.genfromtxt(DATA, delimiter=',', skip_header=1, usecols=4)  # stock_qty

p07 = prices[stocks >= 100]*0.7
p09 = prices[(stocks >= 20) & (stocks <= 99)]*0.9
p_original = prices[stocks < 20]

#print(p07)
#print(p09)
#print(p_original)

final_p = np.concatenate([p07, p09, p_original])
print(final_p)
print(final_p.sum())b
print("原本全站價格:",{prices.sum()})

[1312.5 1202.6  203.   426.3 1075.9  392.7  766.5 1238.3  526.4 1677.2
  228.9  219.8 1292.2  267.4  189.7 1460.9  133.7  700.  1132.6  331.8
  410.9  558.   141.3 1724.4 1386.9 1329.3 1755.9 1935.  1627.  1506. ]
27153.100000000002
原本全站價格: {np.float64(34644.0)}


In [12]:
# 🏁 大地遊戲 — 把你算出的雙 11 總售價丟進來，答對就能找到解答！
check('S1', round(final_p.sum(), 1))

NameError: name 'check' is not defined

---
## 小結與速查表

| 想做什麼 | 怎麼寫 |
|---|---|
| 建立陣列 | `np.array([1,2,3])` |
| 看形狀/型別 | `arr.shape`, `arr.dtype` |
| 切片 | `arr[1:4]`, `arr[::2]` |
| 布林篩選 | `arr[arr > 10]` |
| 多條件 | `arr[(arr>10) & (arr<50)]` |
| 加減乘除 | `a + b`, `a * 2`（向量化，無需 loop）|
| 統計 | `.sum() .mean() .max() .min() .std()` |
| 條件賦值 | `np.where(cond, a, b)` |
| 排序索引 | `np.argsort(arr)` |

**下節預告 S2**：今天的 NumPy 是「數字矩陣」，但真實資料有字串、日期、缺值 → **Pandas 登場**，我們會拿一份**故意弄髒的訂單 CSV**，學怎麼把它清乾淨。
